spring:
  data:
    elasticsearch:
      cluster-name: elastaicsearch
      cluster-nodes: 49.233.163.188:9300
      repositories:
        enabled: true

mall:
  swagger:
    enabled: true
    title: 日志中心
    description: 日志中心接口文档
    version: 1.0
    base-package: com.kech.log.controller