spring:
  datasource:
    url: jdbc:mysql://49.233.163.188:3306/mallcloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: wangwenxin123
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.kech.common.model
  global-config:
    db-config:
      id-type: auto

mall:
  cache-manager:
    configs:
      - key: menu
        second: 600
      - key: user
        second: 1800
aliyun:
    oss:
        accessKeyId: 5Jii89BFukxmun5j
        accessKeySecret: JvE9FcILlHu5gClmAJr89ZkEv00l9s
        bucketName: yjlive160322
        callback: http://localhost:8080/aliyun/oss/callback
        dir:
            prefix: mall/images/
        endpoint: oss-cn-beijing.aliyuncs.com
        maxSize: 10
        policy:
            expire: 300
